---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
---
spring:
  jpa:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      driverClassName: com.mysql.jdbc.Driver
      password: password
      url: "jdbc:mysql://localhost/company"
      username: user
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles: local
---
spring:
  profiles: cloud
message: Steve
